### ISSUE TITLE
GBM fails on norm array multiplication

### ISSUE THREAD

**Issue by mryellow** [NathanEpstein/stochastic#1]
Running in NodeJS v0.10.40

GBM returns `NaN`.

`(sigma*norm(0,Math.sqrt(T)))`

https://github.com/NathanEpstein/stochastic/blob/0f42ca6077ade6b9b8dc62bde08a3ec63a747481/index.js#L93

`norm` is returning an array, while `sigma` is a float.

Missing a vector math dependency?

**Comment by NathanEpstein** [comment]
Fix has been pushed - thanks for pointing this out!
